---

 - name: Ensures that the baremetal is ready
   hosts: baremetal-machine
   user: "{{ user }}"
   sudo: yes

   tasks:

     - name: ensures ansible repository is present
       apt_repository: repo='ppa:ansible/ansible' state=present

     - apt: update_cache=yes

     - apt: upgrade=dist state=latest

     - name: Install basic packages
       apt: name={{ item }} state=latest
       with_items:
         - vim
         - git
         - openvpn
         - tmux
         - software-properties-common
         - ansible
         - curl

     - name: make the user a sudoer without password
       lineinfile: dest=/etc/sudoers state=present line='{{user}} ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'

     - name: Vundle repository must be present
       git: repo=http://github.com/VundleVim/Vundle.vim.git dest=/home/{{user}}/.vim/bundle/Vundle.vim

     - name: Copy file/.vimrc to /home/user directory
       copy: src=../files/.vimrc dest=/home/{{ user }}/.vimrc owner={{ user }} group={{ user }}

     - name: Vundle the vim plugins
       shell: vim +PluginInstall +qall
       register: vundle_command
       failed_when: 'vundle_command.rc != 0'

     - name: Ensures the java binary file is present
       copy: src=../files/jre-6u45-linux-x64.bin dest=/home/{{ user }}/ owner={{ user }} group={{ user }}
       register: java_file

     - name: Make sure that the java binary is executable
       command: bash -lc "chmod +x /home/{{user}}/jre-6u45-linux-x64.bin"
       register: command_result
       failed_when: "command_result.rc != 0"
       when: java_file|changed

     - name: Make sure that the java binary is extracted
       shell: "/home/{{user}}/jre-6u45-linux-x64.bin"
       register: command_result
       failed_when: "'Done.' not in command_result.stdout or command_result.rc != 0"
       sudo: no
       when: java_file|changed

     - name: Java home must be set
       lineinfile: dest=/home/{{ user }}/.bashrc state=present line="export JAVA_HOME='/home/{{user}}/jre1.6.0_45'"

     - name: The PATH must include the JAVA_HOME bin
       lineinfile: dest=/home/{{ user }}/.bashrc state=present line="export PATH=$PATH:$JAVA_HOME/bin"
